
#*****************************************************************************************
# TYPES
#*****************************************************************************************

type School {
	identifier: String!
	name: String!
}

type UserSchool {
	identifier: String!
	name: String!
	userRole: String!
}

#*****************************************************************************************
# QUERIES
#*****************************************************************************************

type Query {
	school(identifier: String!): School! @Authorized
	userSchool(identifier: String!): UserSchool! @Authorized
	membershipSchools: [UserSchool]! @Authorized
}

#*****************************************************************************************
# INPUTS
#*****************************************************************************************

input ISchool {
	identifier: String!
	name: String!
	registerCode: String!
}

#*****************************************************************************************
# MUTATIONS
#*****************************************************************************************

type Mutation {
	createSchool(data: ISchool!): DefaultResponse! @HasRole(role: "basic") @Authorized
}

#*****************************************************************************************
